name: MSYS2 x86 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        # This ensures all 'run' steps use the MSYS2 bash shell by default
        shell: msys2 {0}
        
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: >-
            base-devel
            gcc
            make
            msys2-runtime-devel
            libcrypt-devel
            libiconv-devel
            gettext-devel
          update: true
          
      - name: Build project
        run: |
          cd ido-static-recomp
          # We force -m32 to tell the 64-bit GCC to build a 32-bit binary
          # We also define _FILE_OFFSET_BITS=64 to keep the Unix headers happy
          make clean || true
          make setup -j$(nproc)
          make -j$(nproc)

      - name: Check Architecture
        run: |
          file ido-static-recomp/build/out/cc

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: full-build-output-x86
          # Uploading '.' captures everything in the current directory
          # You can change this to a specific folder (e.g., './dist') if preferred
          path: .
          # Optional: exclude the .git folder to keep the artifact size down
          retention-days: 5
